#!/usr/bin/env node

const path = require('path')
const chokidar = require('chokidar')
const execa = require('execa')

// Config
const dirRoot = path.join(__dirname, '../')
const dirSrc = path.join(dirRoot, './src')
const buildCommand = 'npm run build'

// Local state
let scheduledRebuild = false
let buildRunning = false
let index = 0

// Logs
console.log('Starting watch-and-build')
console.log(`  App directory: "${dirRoot}"`)
console.log(`  Build command: "${buildCommand}"`)

// Watch
chokidar.watch(dirSrc).on('change', async (event, path) => {
  index++
  console.log(`[${index}] files changed`)

  if (buildRunning) {
    scheduledRebuild = true
    return
  }

  await runBuild()
})

console.log('\nWatch started\n')

// Build function
async function runBuild () {
  buildRunning = true
  const start = Date.now()
  const indexBuild = index
  console.log(`[${indexBuild}] starting compilation`)

  await execa.shell(buildCommand)

  const end = Date.now()
  const time = ((end - start) / 1000).toFixed(2)
  console.log(`[${indexBuild}] compilation finished (${time}s)`)

  buildRunning = false
  if (scheduledRebuild) {
    scheduledRebuild = false
    await runBuild()
  }
}
