name: Main workflow

on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm ci
      - run: npm run validate
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: hello-build
          path: build
      - uses: actions/upload-artifact@v2
        with:
          name: hello-src
          path: |
            .
            !node_modules
            !build
